version: '3'

services:
  vc-issuer-app:
    build: ./vc-issuer-app-spring
    image: twogenidentity/vc-issuer-app-spring:latest
    container_name: vc-issuer-app-spring
    environment:
      VC_AUTHORITY: ${VC_AUTHORITY}
      VC_CREDENTIAL_MANIFEST: ${VC_CREDENTIAL_MANIFEST}   
      VC_ISSUANCE_CALLBACK_URL: ${DOMAIN_URL}/issuer/api/vc/issuance/callback
      IDP_OAUTH2_CLIENT_ID: ${IDP_OAUTH2_CLIENT_ID}
      IDP_OAUTH2_CLIENT_SECRET: ${IDP_OAUTH2_CLIENT_SECRET}
      IDP_OAUTH2_REDIRECT_URI: ${DOMAIN_URL}/issuer/login/oauth2/code/idp
      IDP_ISSUER_URI: ${IDP_ISSUER_URI}
      AZURE_OAUTH2_CLIENT_ID: ${AZURE_ISSUER_OAUTH2_CLIENT_ID}
      AZURE_OAUTH2_CLIENT_SECRET: ${AZURE_ISSUER_OAUTH2_CLIENT_SECRET}
      AZURE_ISSUER_URI: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0  
    ports:
      - 8082:8080
  vc-verifier-app:
    build: ./vc-verifier-app-spring
    image: twogenidentity/vc-verifier-app-spring:latest
    container_name: vc-verifier-app-spring
    environment:
      VC_AUTHORITY: ${VC_AUTHORITY}
      VC_ISSUER: ${VC_AUTHORITY}
      VC_PRESENTATION_CALLBACK_URL: ${DOMAIN_URL}/verifier/api/vc/presentation/callback
      VC_CREDENTIAL_MANIFEST: ${VC_CREDENTIAL_MANIFEST}  
      VC_ISSUANCE_CALLBACK_URL: ${DOMAIN_URL}/verifier/api/vc/presentation/callback
      AZURE_OAUTH2_CLIENT_ID: ${AZURE_VERIFIER_OAUTH2_CLIENT_ID}
      AZURE_OAUTH2_CLIENT_SECRET: ${AZURE_VERIFIER_OAUTH2_CLIENT_SECRET}
      AZURE_ISSUER_URI: https://login.microsoftonline.com/${AZURE_TENANT_ID}/v2.0  
    ports:
      - 8083:8080
  vc-verifier-app-node:
    build: ./vc-verifier-app-node
    image: twogenidentity/vc-verifier-app-node:latest
    container_name: vc-verifier-app-node
    environment:
      DOMAIN_URL: ${DOMAIN_URL}
      VC_AUTHORITY: ${VC_AUTHORITY}
      PRIVATE_KEY_HEX: ${VC_ISSUER_PRIVATE_KEY_HEX}
      DID: ${VC_ISSUER_DID}
      DID_LONG: ${VC_ISSUER_DID_LONG} 
      DID_KEY: ${VC_ISSUER_DID_KEY}
    ports:
      - 8084:8081          