version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:11
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  idp:
    build: ./keycloak
    image: twogenidentity/keycloak
    container_name: idp
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_SCHEMA: public
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME_STRICT: 'false'
      KC_HTTP_ENABLED: 'true'
      KC_PROXY: edge
      KC_HOSTNAME_URL: ${DOMAIN_URL}
      KC_HOSTNAME_ADMIN_URL: ${DOMAIN_URL}
      KC_HEALTH_ENABLED: 'true'
      KC_HOSTNAME_STRICT_BACKCHANNEL: 'false'
      KC_LOG_LEVEL: INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 5s
      timeout: 2s
      retries: 15  
    ports:
      - 8081:8080
    depends_on:
      - postgres